Added clickable objects with UI E indicator
Team-Swamp/HyperUnicornGameJam pull request #7
Opened 2023-11-14 14:13 UTC by DaanDuits

2023-11-14 17:57 UTC, Tatum13 requested changes

2023-11-14 17:57 UTC, Tatum13 commented on Assets/Scripts/UI/LookAtCamera.cs
> +    }
```suggestion
    void Start() =>  mainCamera = Camera.main;
```

2023-11-14 17:57 UTC, Tatum13 commented on Assets/Scripts/Ingredients/InteractableBehaviour.cs
> +    // Start is called before the first frame update
```suggestion

```

2023-11-14 17:57 UTC, Tatum13 commented on Assets/Scripts/Ingredients/InteractableBehaviour.cs
> +    GameObject hoverObjectInstance;
```suggestion
    [SerializeField] private GameObject hoverObject;
    private Transform worldCanvas => GameObject.Find("WorldCanvas").transform;
    [SerializeField] private Transform player;
    private GameObject hoverObjectInstance;
```

2023-11-14 17:57 UTC, Tatum13 commented on Assets/Scripts/Ingredients/InteractableBehaviour.cs
> +    GameObject hoverObjectInstance;
Is denk wel handiger om neer te zetten wanneer een variable public of private is, zodat als een ander het nodig heeft in een ander script, dan ook gelijk kan aflezen wat die kan gebruiken. 

Wannee je niks neerzet is het default private, maar is denk netter om het er gewoon bij te zetten of het public of private is.

2023-11-14 17:57 UTC, Tatum13 commented on Assets/Scripts/Ingredients/InteractableBehaviour.cs
> +}
Hmm ik vraag mij af of je bij de "OnMouseEnter" een else kan neerzetten en de "OnMouseExit" kan weglaten, maar dat weet ik niet zeker. 

Je zou die if zonder brackets kunnen maken en de "hoverObjectInstance.SetActive(true);" gewoon achter de if plaatsen.

Als de "OnMouseExit" blijft, dan zou je het ook op 1 regel kunnen gooien door "private void OnMouseExit() => hoverObjectInstance.SetActive(false);" te doen

2023-11-14 17:57 UTC, Tatum13 commented on Assets/Scripts/Ingredients/InteractableBehaviour.cs
> +    void Start()
```suggestion
    private void Start()
```
Bij al je functies kan je niet zien of het public of private is, dit zou je kunnen aanpassen, want het is wel netter

2023-11-15 10:03 UTC, swzwij requested changes

2023-11-15 10:03 UTC, swzwij commented on Assets/Scripts/Ingredients/InteractableBehaviour.cs
> +public class InteractableBehaviour : MonoBehaviour
Missing namespace

2023-11-15 10:03 UTC, swzwij commented on Assets/Scripts/Ingredients/InteractableBehaviour.cs
> +using Unity.VisualScripting;
Is `Unity.VisualScripting` needed for this class?

2023-11-15 10:03 UTC, swzwij commented on Assets/Scripts/Ingredients/InteractableBehaviour.cs
> +    private Transform player => GameObject.Find("PlayerObject").transform;
`GameObject.Find` is really bad for performance, please refrain from using it

2023-11-15 10:03 UTC, swzwij commented on Assets/Scripts/UI/LookAtCamera.cs
> +    void LateUpdate()
Why the `LateUpdate`?

2023-11-15 10:03 UTC, swzwij commented on Assets/Scripts/UI/LookAtCamera.cs
> +        transform.Rotate(0, 180, 0);
Hardcoded values?

2023-11-16 14:35 UTC, merged